### ISSUE TITLE
Support for importing highways from a git repo

### ISSUE THREAD

**Issue by bsrz** [kdawgwilk/Autobahn#12]
It would be really useful to have the power to import highways from another repo, such as:
https://docs.fastlane.tools/advanced/#importing-another-fastfile

**Comment by BenchR267** [comment]
I agree, this would be a great addition, but it's quite hard to implement…

**Comment by bsrz** [comment]
@BenchR267 what about some kind of plist system? The highways could be defined as plists and then imported via a git repo and executed? Just thinking out loud here...

**Comment by kdawgwilk** [comment]
I like this idea as well but I think this will be implemented further down the road since we are still lacking many core features required for wide adoption

**Comment by bsrz** [comment]
This is super old. Looks like the project is pretty much abandoned. Closing.
